CREATE TABLE `suppliers` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `corporate_name` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `corporate_name_2` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `legal_status` int(1) DEFAULT '0',
  `logo` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `advertiser` int(1) NOT NULL DEFAULT '0',
  `type` int(1) NOT NULL DEFAULT '0',
  `grip_ent` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `description_ent_1` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `description_ent_2` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `description_ent_3` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `grip_hearing_aids` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `description_hearing_aids_1` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `description_hearing_aids_2` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `description_hearing_aids_3` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `address_1` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `additional_address` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `additional_address_2` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `city_1` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `zip_1` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `po_box` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `zip_cedex_cp_cedex` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `city_cedex` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `country` int(11) DEFAULT NULL,
  `phone` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `phone_2` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `fax` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `fax_2` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `email_1` varchar(150) COLLATE utf8_unicode_ci DEFAULT NULL,
  `email_2` varchar(150) COLLATE utf8_unicode_ci DEFAULT NULL,
  `address_2` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `address_2_additional` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `address_2_additional_2` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `zip` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `city_2` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `zip_2` varchar(150) COLLATE utf8_unicode_ci DEFAULT NULL,
  `website` varchar(150) COLLATE utf8_unicode_ci DEFAULT NULL,
  `website_2` varchar(150) COLLATE utf8_unicode_ci DEFAULT NULL,
  `created` datetime DEFAULT NULL,
  `updated` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci
