CREATE TABLE `networks` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `corporate_name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `grip` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `description` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `grip_related_centers` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `description_related_centers` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `advertiser` int(1) DEFAULT '0',
  `address_1` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `additional_address` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `po_box` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `zip_cedex_address_1` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `city_cedex_address_1` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `city_1` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `zip_1` varchar(150) COLLATE utf8_unicode_ci DEFAULT NULL,
  `phone_number_1a` varchar(150) COLLATE utf8_unicode_ci DEFAULT NULL,
  `phone_1b` varchar(150) COLLATE utf8_unicode_ci DEFAULT NULL,
  `fax_1a` varchar(150) COLLATE utf8_unicode_ci DEFAULT NULL,
  `fax_1b` varchar(150) COLLATE utf8_unicode_ci DEFAULT NULL,
  `a_email_1a` varchar(150) COLLATE utf8_unicode_ci DEFAULT NULL,
  `email_1b` varchar(150) COLLATE utf8_unicode_ci DEFAULT NULL,
  `website_1a` varchar(150) COLLATE utf8_unicode_ci DEFAULT NULL,
  `website_1b` varchar(150) COLLATE utf8_unicode_ci DEFAULT NULL,
  `address_2` varchar(150) COLLATE utf8_unicode_ci DEFAULT NULL,
  `additional_address_2` varchar(150) COLLATE utf8_unicode_ci DEFAULT NULL,
  `po_box_address_2` varchar(150) COLLATE utf8_unicode_ci DEFAULT NULL,
  `zip_cedes_address_2` varchar(150) COLLATE utf8_unicode_ci DEFAULT NULL,
  `city_cedex_address` varchar(150) COLLATE utf8_unicode_ci DEFAULT NULL,
  `city_2` varchar(150) COLLATE utf8_unicode_ci DEFAULT NULL,
  `zip_2` varchar(150) COLLATE utf8_unicode_ci DEFAULT NULL,
  `phone_2a` varchar(150) COLLATE utf8_unicode_ci DEFAULT NULL,
  `phone_2b` varchar(150) COLLATE utf8_unicode_ci DEFAULT NULL,
  `fax_2a` varchar(150) COLLATE utf8_unicode_ci DEFAULT NULL,
  `fax_2b` varchar(150) COLLATE utf8_unicode_ci DEFAULT NULL,
  `email_2a` varchar(150) COLLATE utf8_unicode_ci DEFAULT NULL,
  `email_2b` varchar(150) COLLATE utf8_unicode_ci DEFAULT NULL,
  `website_2a` varchar(150) COLLATE utf8_unicode_ci DEFAULT NULL,
  `website_2b` varchar(150) COLLATE utf8_unicode_ci DEFAULT NULL,
  `logo` varchar(150) COLLATE utf8_unicode_ci DEFAULT NULL,
  `created` datetime DEFAULT NULL,
  `updated` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci
